=== nataasvpp/nataasvpp/control-plane/vppconf/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.office.opendns.com/otroan/nataasvpp/tree/main/control-plane/nataasvpp-schema.json",
    "title": "NATaaS VPP",
    "description": "NATaaS VPP control plane schema",
    "type": "object",
    "properties": {
        "interfaces": {
            "description": "A hash of interfaces gatewaying traffic into the session data plane",
            "type": "object",
            "properties": {
                "tenant": {
                    "type": "number"
                },
                "tunnel-headend": {
                    "type": "boolean"
                }
            }
        },
        "nats": {
            "description": "A hash of NAT definitions",
            "type": "object",
            "propertyNames": {
                "format": "uuid"
            },
            "properties": {
                "pool-address": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "ipv4"
                    }
                }
            }
        },
        "tunnels": {
            "description": "A hash of tunnel definitions",
            "type": "object",
            "propertyNames": {
                "format": "uuid"
            },
            "properties": {
                "tenant": {
                    "type": "number"
                },
                "method": {
                    "type": "string"
                },
                "src": {
                    "type": "string",
                    "format": "ipv4"
                },
                "dst": {
                    "type": "string",
                    "format": "ipv4"
                },
                "sport": {
                    "type": "number"
                },
                "dport": {
                    "type": "number"
                },
                "src-mac": {
                    "type": "string"
                },
                "dst-mac": {
                    "type": "string"
                }
            }
        },
        "tenants": {
            "description": "A hash of tenant definitions",
            "type": "object",
            "propertyNames": {
                "pattern": "[0-9]+"
            },
            "properties": {
                "context": {
                    "type": "number"
                },
                "flags": {
                    "type": "string",
                    "enum": ["no-create"]
                },
                "forward-services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reverse-services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "nat-instance": {
                    "type": "string",
                    "format": "uuid"
                },
                "tcp-mss": {
                    "type": "array",
                    "description": "Forward and Reverse direction TCP MSS clamping.",
                    "items": {
                        "type": "number",
                        "minItems": 1,
                        "maxItems": 2
                    }
                }
            }
        },
        "interface_list": {
            "description": "A hash of interfaces available on the host",
            "type": "object"
        },
        "boottime": {
            "description": "A epoch time of when the vpp process started",
            "type": "number"
        }
    },
    "required": [
        "interfaces",
        "tunnels",
        "nats",
        "tenants"
    ],
    "additionalProperties": false
}

=== nataasvpp/nataasvpp/doc/configuration.json
{
    "tunnels": {
        "foobar2": {
            "tenant": 1,
            "method": "vxlan-dummy-l2",
            "src": "192.168.0.1",
            "dst": "192.168.0.2",
            "dport": 4790
        }
    },
    "interfaces": {
        "tap0": {
            "tenant": 1000
        },
        "tap10": {
            "tenant": 1000
        },
        "tap1": {
            "tunnel-headend": true
        }
    },
    "nats": {
        "1": {
            "pool-address": [
                "123.123.123.123",
                "1.1.1.1"
            ]
        }
    },
    "tenants": {
        "0": {
            "context": 0,
            "forward-services": [
                "vcdp-l4-lifecycle",
                "vcdp-nat-output"
            ],
            "reverse-services": [
                "vcdp-l4-lifecycle",
                "vcdp-tunnel-output"
            ],
            "nat-instance": "1"
        },
        "1": {
            "context": 0,
            "forward-services": [
                "vcdp-l4-lifecycle",
                "vcdp-nat-output"
            ],
            "reverse-services": [
                "vcdp-l4-lifecycle",
                "vcdp-tunnel-output"
            ],
            "nat-instance": "1"
        },
        "1000": {
            "context": 0,
            "flags": "no-create",
            "forward-services": [
                "vcdp-bypass"
            ]
        }
    }
}
